import {
  UtensilsIcon,
  CarIcon,
  TicketIcon,
  FileTextIcon,
  HeartPulseIcon,
  BookOpenIcon,
  ShoppingBagIcon,
  MoreHorizontalIcon,
  HomeIcon,
  TvIcon,
  ShirtIcon,
  PlaneIcon,
  GiftIcon,
  WrenchIcon,
  SmartphoneIcon,
  CoffeeIcon,
  DumbbellIcon,
  PawPrintIcon,
  BriefcaseIcon,
  CircleIcon,
  type LucideIcon,
} from 'lucide-react';

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  utensils: UtensilsIcon,
  car: CarIcon,
  ticket: TicketIcon,
  'file-text': FileTextIcon,
  'heart-pulse': HeartPulseIcon,
  'book-open': BookOpenIcon,
  'shopping-bag': ShoppingBagIcon,
  'more-horizontal': MoreHorizontalIcon,
  home: HomeIcon,
  tv: TvIcon,
  shirt: ShirtIcon,
  plane: PlaneIcon,
  gift: GiftIcon,
  wrench: WrenchIcon,
  smartphone: SmartphoneIcon,
  coffee: CoffeeIcon,
  dumbbell: DumbbellIcon,
  'paw-print': PawPrintIcon,
  briefcase: BriefcaseIcon,
  circle: CircleIcon,
};

export const ICON_OPTIONS = [
  { value: 'utensils', label: 'Talheres' },
  { value: 'car', label: 'Carro' },
  { value: 'ticket', label: 'Ingresso' },
  { value: 'file-text', label: 'Documento' },
  { value: 'heart-pulse', label: 'Saúde' },
  { value: 'book-open', label: 'Livro' },
  { value: 'shopping-bag', label: 'Sacola' },
  { value: 'home', label: 'Casa' },
  { value: 'tv', label: 'TV' },
  { value: 'shirt', label: 'Roupa' },
  { value: 'plane', label: 'Avião' },
  { value: 'gift', label: 'Presente' },
  { value: 'wrench', label: 'Ferramenta' },
  { value: 'smartphone', label: 'Celular' },
  { value: 'coffee', label: 'Café' },
  { value: 'dumbbell', label: 'Haltere' },
  { value: 'paw-print', label: 'Pata' },
  { value: 'briefcase', label: 'Maleta' },
  { value: 'more-horizontal', label: 'Outros' },
  { value: 'circle', label: 'Círculo' },
];
